cmd/printer/snapshot.go
Add description of snapshot so that the user can figure out
which snapshot the ID refers to without logging onto the
web frontend.
=> Add snapshot description to "vultr-cli snapshot list"

cmd/bareMetal.go, cmd/blockStorage.go, cmd/dnsDomain.go, cmd/dnsRecord.go, cmd/firewallGroup.go, cmd/firewallRule.go, cmd/iso.go, cmd/network.go, cmd/reservedIP.go, cmd/script.go, cmd/server.go, cmd/snapshot.go, cmd/sshKey.go, cmd/user.go
The front end and API refer to the action as destroying a server,
not deleting it, so this makes the command line more consistent
for users.
=> Add "server destroy" as alias for "server delete"

cmd/dnsRecord.go
Add quotes around TXT data if not exist. The issue is that the client is not aware of the type of the record, and the API will not accept TXT without quotes.
The commands `dns record create` and `dns record update` have consistent behavior with the `data` flag
* This will work `new_value`, `"\"new_value\""`
* This will not work `\"new_value\"`
Guess with a regular expression if the record is `TXT`, and wrap the data in quotes. If the record data has already quotes, it will not escape them. In this case the user must escape the `TXT` value.
Fixes #40
=> Fix #40 - Add quotes to dns data

cmd/root.go
Add contextual command line instruction for exporting the Vultr API key to the proper BASH variable.
(if this means `go fmt`, per the [Contributing Guidelines](https://github.com/vultr/vultr-cli/blob/master/CONTRIBUTING.md#overview), then yes)  
(unsure if `tests` is defined somewhere other than the readme/contributing docs, but didn't see anything straightforward to run to ensure this step was completed, please advize.)
---
The code builds and executes successfully on Mac OSX v10.13.6, using `golang v1.12.9 darwin/amd64` (installed via Homebrew).
As the only change is a text printout, nothing fundamental should change, hence the slightly half-assed PR.
=> Add contextual instructions for Vultr API key setup.

cmd/server.go
'vultr-cli server' prints some weird nonsense about reverse dns under the create option. this pr fixes it.
=> corrected description for server operations

cmd/printer/blockStorage.go, cmd/printer/plans.go, go.mod, go.sum, vendor/github.com/vultr/govultr/v2/CHANGELOG.md, vendor/github.com/vultr/govultr/v2/README.md, vendor/github.com/vultr/govultr/v2/account.go, vendor/github.com/vultr/govultr/v2/application.go, vendor/github.com/vultr/govultr/v2/backup.go, vendor/github.com/vultr/govultr/v2/bare_metal_server.go, vendor/github.com/vultr/govultr/v2/block_storage.go, vendor/github.com/vultr/govultr/v2/domain_records.go, vendor/github.com/vultr/govultr/v2/domains.go, vendor/github.com/vultr/govultr/v2/firewall_group.go, vendor/github.com/vultr/govultr/v2/firewall_rule.go, vendor/github.com/vultr/govultr/v2/govultr.go, vendor/github.com/vultr/govultr/v2/instance.go, vendor/github.com/vultr/govultr/v2/iso.go, vendor/github.com/vultr/govultr/v2/load_balancer.go, vendor/github.com/vultr/govultr/v2/network.go, vendor/github.com/vultr/govultr/v2/object_storage.go, vendor/github.com/vultr/govultr/v2/os.go, vendor/github.com/vultr/govultr/v2/plans.go, vendor/github.com/vultr/govultr/v2/regions.go, vendor/github.com/vultr/govultr/v2/reserved_ip.go, vendor/github.com/vultr/govultr/v2/snapshot.go, vendor/github.com/vultr/govultr/v2/ssh_key.go, vendor/github.com/vultr/govultr/v2/startup_script.go, vendor/github.com/vultr/govultr/v2/user.go, vendor/modules.txt
- update govultr to 2.4.0
- add support for block storage mount_id and plans disk_count fields
=> Update govultr, block, plans

cmd/root.go
Currently vultr-cli always uses `~/.vultr-cli.yaml` and creates the file if it doesn't exist. This patch checks for `$XDG_CONFIG_HOME/vultr-cli.yaml` first but falls back to the old behavior if it doesn't exist. This shouldn't interfere with any existing setups.
=> Support config files in $XDG_CONFIG_HOME

cmd/instance.go
Default the `notify` field to false. This will help avoid confusion when you don't use `=` in assignment when you want it to be false
#184
=> Instance create : change notify default 

cmd/backups.go
Discovered while working on: https://github.com/withfig/autocomplete/pull/550
=> Fix typo in `backups` alias: "a" -> "b"

README.md
vultr-cli was ported for OpenBSD and is not imported in ports tree and available from the `pkg_add` utility for the -current flavor.
=> Add OpenBSD install instructions.

.github/workflows/releaser.yml
Fixes regex bug with double digit releases
=> Fixed regex for releaser

CHANGELOG.md, cmd/version.go
=> Release v2.12.1

README.md
Hit an error when walking through the readme for creating an instance:
```
./vultr-cli instance create --region ord --plan vc2-1c-1gb --os 477 --hostname test --notify=true
Error: unknown flag: --hostname
```
Looks like the flag name was changed in #210
None, just noticed while on-boarding :)
=> Correct flag name for setting hostname

cmd/plans.go, cmd/plansMetal.go
Add a new command to specifically list only bare-metal type plans.  This functionality was hidden in the `plan list --type=bare-metal` command.  The same output is produced with the new `plans metal list` command. 
This change also adds long help text and examples for the `plans` commands.
=> Add `plans metal list` command and update some helptext on `plans`

cmd/instance.go, cmd/loadBalancer.go, cmd/network.go, cmd/printer/vpc.go, cmd/root.go, cmd/vpc.go
This commit adds the VPC support offered by govultr 2.15.x and
deprecates the private network commands.  Note, this means that usage of
the `vultr-cli network` commands will output a deprecation notice which
may throw off output parsers.
Add VPC support and deprecate private network support
=> Add VPC support and deprecate networks

cmd/firewallRule.go, cmd/printer/firewallRule.go
This adds the `--ip-type` flag to conform with recent API changes and deprecates the `type` flag.  Additionally this adds docs for the firewall rule commands and changes the firewall rule printer to use `IPType`
* Create a firewall group
`go run main.go firewall group create`
* Use the created group ID to add a new fw rule using the `--ip-type` flag
`go run main.go firewall rule create -i=<GROUP-UUID> --ip-type=v4 -p=tcp -z=24 -s=127.0.0.0 -r=30002`
* Check the output and make sure type is showing as `v4`
* Confirm the `--type` flag still works for backwards compatibility
`go run main.go firewall rule create -i=<GROUP-UUID> --type=v4 -p=tcp -z=24 -s=127.0.0.0 -r=30003`
* Check error output if both `--type` and `--ip-type` are passed in
`go run main.go firewall rule create …
=> Add firewall rule ip-type support

cmd/kubernetes.go, cmd/printer/kubernetes.go
Add support for the VKE auto scaler options in the API.
* Create a new cluster with a node pool and autoscaling enabled:
`go run main.go kubernetes create --label="my-cluster" --region="ewr" --version="v1.23.5+3" --node-pools="quantity:1,plan:vc2-1c-2gb,label:my-nodepool,auto-scaler:true,min-nodes:1,max-nodes:2"`
* Update an existing node pool to enable autoscaling:
`go run main.go kubernetes node-pool update <CLUSTER-UUID> <NP-UUID> --auto-scaler=true --min-nodes=3 --max-nodes=4`
* Update an existing node pool to disable autoscaling:
`go run main.go kubernetes node-pool update <CLUSTER-UUID> <NP-UUID> --auto-scaler=false`
* Check the printer output for `list`:
` go run main.go kubernetes list`
=> Add VKE auto scaler options

cmd/kubernetes.go, cmd/printer/kubernetes.go
Add commands to list and perform upgrades of the VKE cluster K8 version
=> Add support for VKE version upgrades

cmd/reservedIP.go, go.mod, go.sum, vendor/github.com/vultr/govultr/v2/CHANGELOG.md, vendor/github.com/vultr/govultr/v2/govultr.go, vendor/github.com/vultr/govultr/v2/reserved_ip.go, vendor/modules.txt
Update govultr and add support for the reserved IP label update functionality
=> Update govultr and add support for reserved IP label updates

cmd/firewallRule.go
The output of `vultr-cli fw r c -h` contains the example command-line:
```sh
vultr-cli fw r c -i=f04ae5aa-ff6a-4078-900d-78cc17dca2d5 --t=v4 -p=tcp -z=24 -s=127.0.0.0 -r=30000
```
Running that example fails, due to the `--t`:
```
Error: unknown flag: --t
```
This commit changes the flag to `-t`, which works as expected.
=> Remove extraneous dash from example command-line

cmd/blockStorage.go, cmd/instance.go
Fix some examples that were passing params with spaces instead of "=" (`--label "my-label` vs `--label="my-label"`).  Just trying to be consistent.
=> Make cli param examples consistently use =

cmd/database.go
There were a couple of bugs with the database update endpoint, namely some MySQL errors popping up when trying to update a PostgreSQL subscription and two erroneous flags for database engine and database engine version that are not actually updatable through this endpoint -- just a copy pasta fail.
=> Fix database update errors and remove db engine/version

README.md, cmd/bareMetal.go, cmd/database.go, cmd/instance.go, cmd/printer/bareMetal.go, cmd/printer/instance.go, cmd/printer/vpc2.go, cmd/root.go, cmd/vpc2.go
This PR adds support for VPC2 to the Vultr-CLI project. It includes all of the main VPC2 endpoints as well as the new VPC2 endpoints for the instance and bare metal components of the API. Also cleaned up a couple of comment/example errors left behind in the database component while I was at it.
=> Add support for VPC 2.0

cmd/instance.go
This flag doesn't accept the IP address directly, it has to be the uuid of the IP address.
=> cmd/instance: Fix reserved IPv4 flag docs

.goreleaser.yml
There was a discrepancy between running it locally and when running it on github.
An issue with testing the goreleaser locally made it seem like the project name was duplicated
=> Add project name back to the archive file names in goreleaser

cmd/database.go, cmd/kubernetes.go, cmd/loadBalancer.go, cmd/printer/database.go, cmd/printer/kubernetes.go, cmd/printer/loadBalancer.go
The list commands on the database, VLB and VKE return a bunch of data in their printers which is hard to parse at a glance.  This will expose a `--summarize` flag to tabulate some of the general data for each server/cluster it returns.
* `go run main.go kubernetes list --summarize`
* `go run main.go load-balancer list --summarize`
* `go run main.go database list --summarize`
=> Add summarize list options for VKE, VLB & database

cmd/root.go
A holdover flag from the cobra init for this CLI.  Doesn't do anything.
=> Remove the useless cobra init help toggle flag

cmd/printer/database.go
This PR adds support for the Managed Database `public_host` field to allow customers to distinguish between the main host address and the public one for subscriptions attached to a VPC network. It also cleans up the summarized database list view to hide the credentials since they take up a ton of space.
=> Managed Database public/private hostnames, cleanup summarize view

cmd/database.go
Current implementation on master has an issue where not including a `vpc-id` will treat it as passing an empty one, which detaches the current VPC from a Managed Database. Swaps that to only include VPCID in the update request if the value was explicitly passed, whether it is empty or not (with empty being remove VPC and an ID string setting or changing VPC).
=> Adjust DBaaS VPC pointer to detect changes

cmd/account.go, cmd/backups.go, cmd/bareMetal.go, cmd/billing.go, cmd/blockStorage.go, cmd/database.go, cmd/dns.go, cmd/firewall.go, cmd/instance.go, cmd/iso.go, cmd/kubernetes.go, cmd/loadBalancer.go, cmd/network.go, cmd/objectStorage.go, cmd/reservedIP.go, cmd/root.go, cmd/script.go, cmd/snapshot.go, cmd/sshKey.go, cmd/user.go, cmd/vpc.go, cmd/vpc2.go
These changes re-work some of the authentication logic used to pass the API key when executing commands.  Before this, ALL commands authenticated with this key, even the `version` command.  This PR moves the client logic to allow setting a basic HTTP client without bearer tokens.  It also moves the missing API key check so that it happens in a pre-`Execute` check on each top-level command.  This check cascades down to all of its children.
closes #359  
#332 
#92 
* Open a new shell and do not `export VULTR_API_KEY`
* Test these commands:
All of which should show something along the lines of:
```
Error:
Please export your VULTR API key as an environment variable or add 'api-key' to your config file, eg:
export VULTR_API_KEY='<api_key_from_vultr_account>'
Usage:
vultr-cli database list …
```
=> Allow some commands to be run without authenticating against the API

cmd/printer/bareMetal.go, cmd/printer/instance.go, cmd/printer/printer.go
* adds a string builder function in the printer package that formats a string in the same way that the Fprintf output used to, with the difference being that the items in the array are delimited by a comma
* uses the string builder function on the `list` and `get` command displays for bare-metal and instance
=> Update the bare-metal and instance tags display to use delimiters 

cmd/database.go
This PR adds support for promoting Managed Databse read-only replicas to their own standalone primary subscriptions to match the functionality of the Vultr API and govultr library.
=> Support Managed Database Read Replica Promotion

go.mod, go.sum
=> Update govultr to v3.4.1

cmd/database.go, cmd/printer/database.go
This PR adds support for the Managed Database usage endpoint for individual subscriptions, displaying disk, memory, and CPU usage information. Memory and CPU usage is the average over the last hour while the disk usage will always show current values.
=> Add Managed Database Usage Endpoint Support

cmd/database.go, cmd/printer/database.go
This PR adds support for Redis user access control configurations for Managed Databases. There are updates to the list and get endpoints to retrieve the current configuration when applicable as well as added support for pushing updates to the current ACL configuration under the nested `database user acl update <databaseID> <username> --flags` structure.
=> Support user access control for Redis Managed Databases

README.md, cmd/bareMetal.go, cmd/database.go, cmd/instance.go, cmd/marketplace.go, cmd/printer/marketplace.go, cmd/root.go
This PR updates Vultr-CLI to support user-supplied variables for Vultr Marketplace apps. First is the marketplace/app commands in order to facilitate a public/no-auth list variables endpoint. This updates also contains a new flag for including app variables on create for VPS instances and bare metal servers.
=> Support Marketplace App Variables

cmd/kubernetes/kubernetes.go
Resolve the crash because of overlapping on the `-o` flag shorthand on the `kubernetes` command.
=> Remove shorthand flag output on kubernetes

cmd/plans/plans.go, cmd/plans/printer.go
A bug checking the `len` of the wrong var meant no data was outputted
=> Fix inadvertent short-circuiting bare metal plan printer

cmd/kubernetes/kubernetes.go, cmd/kubernetes/printer.go
This PR will add flags and printer output to support node labels in a node pool on create and update via the `--node-labels` flag.
```sh
go run main.go kubenetes create --help
```
And
```sh
go run main.go kubenetes node-pool create --help
```
```sh
go run main.go kubernetes create --label=cli-flags-test --region="ord" --version="v1.29.2+1" --node-pools="quantity:5,plan:vc2-2c-4gb,label:worker-pool,auto-scaler:true,min-nodes:5,max-nodes:10,node-labels:application=identity-service|worker-size=small"
```
You'll see some output in the new printer that should show the `NODE LABELS` like
```
ID                      8aa47e02-93ea-4caf-be17-28875d79aab0
LABEL                   cli-flags-test
DATE CREATED            2024-03-11T16:45:21+00:00
CLUSTER SUBNET          10.244.0.0/16
SERVICE SUBNET …
```
=> Add node labels to kubernetes node pools

cmd/vpc2/vpc2.go
Fix incorrect govultr delete method for VPC2.  Previously this error was thrown on any and all VPC2 deletes:
```
Error: error deleting vpc2 : {"error":"Invalid private network ID.","status":404}
exit status 1
````
Make sure a VPC2 can be deleted
```
go run main.go vpc2 delete UUID_HERE
```
Fixes #424
=> Fix incorrect govultr delete method for VPC2

cmd/baremetal/baremetal.go
before:
```
$ vultr-cli bare-metal create -r ewr -p vbm-24c-256gb-amd --os=1743
Error: error parsing flags for bare metal create : error parsing persistenterrpxe flag for bare metal create : flag accessed but not defined: persistenterrpxe
```
after:
```
$ ./builds/vultr-cli_linux_amd64 bare-metal create -r ewr -p vbm-24c-256gb-amd --os=1743
Error: error with bare metal create : {"error":"Server add failed: This plan is currently unavailable in this region. Please choose a different plan.","status":400}
```
=> fix mistyped persistent_pxe baremetal flag

cmd/root.go
Move config file checks before reading in the default file.
* Make sure you don't already have a config file somewhere (usually $HOME/.vultr-cli.yaml, but depending on your OS, it could be [elsewhere](https://pkg.go.dev/os#UserConfigDir).
* Run a simple command in the CLI like `go run main.go version`
* Only the version should show, not with the error like below:
```
Error Reading in file: /path/to/your/.vultr-cli.yaml
Vultr-CLI v3.0.2
```
Fixes #433
=> Fix error when a config file is not present

cmd/account/printer.go, cmd/billing/printer.go, cmd/plans/printer.go, cmd/utils/utils.go
Make all float formatting for the printers use two digit precision.
=> Unify float precision on all printers

cmd/dns/dns.go
* Make the `priority` and `ttl` flags on a DNS record optional
* Set default value of `priority` to `-1`, mirroring the API behavior
Resolves #467
=> Make dns record create priority and ttl flags opt

README.md
Command:
go get -u github.com/vultr/vultr-cli/v3
doesn't seem to work any longer, it returns:
go: go.mod file not found in current directory or any parent directory.
'go get' is no longer supported outside a module.
To build and install a command, use 'go install' with a version,
like 'go install example.com/cmd@latest'
For more information, see https://golang.org/doc/go-get-install-deprecation
or run 'go help get' or 'go help install'.
=> Fix command to install vultr-cli using Go

cmd/containerregistry/containerregistry.go
Just made option description consistent with other bool options.
=> Make bool descrition format consistent with other places

cmd/database/database.go, cmd/database/printer.go
This PR matches the recent Govultr updates to remove the Redis-named fields and properties, replacing them with generic versions to eventually support other caching engines.
=> Deprecate Redis-Named Fields

cmd/instance/instance.go
Don't mention how data is processed under the hood. This avoids someone quickly reading the line and thinking it expects base64 input.
=> Update --userdata usage to be more clear

cmd/database/printer.go
This PR cleans up a few Managed Database Redis references and adjusts the plans printer to include Valkey/Kafka as supported engines and some engine-specific field adjustments: disk is hidden for Valkey plans just like in the API and VCPUs and RAM are hidden for Kafka.
=> Adjust plans printer for new supported engines

.golangci.yaml
Removes an unused config block for golangci-lint
=> Remove unused lint config rules exclusion

cmd/containerregistry/containerregistry.go, cmd/database/database.go, cmd/kubernetes/kubernetes.go
Added missing args check in following commands :
1. container-registry credentials docker
2. kubernetes list, kubernetes start 
3. database user list, database topic list, database quota list
Fixes https://github.com/vultr/vultr-cli/issues/498
Fixes https://github.com/vultr/vultr-cli/issues/497
=> Added missing args check in commands

cmd/objectstorage/objectstorage.go, cmd/objectstorage/printer.go
* adds a separate printer for the response from the cluster tiers endpoint which does not have the location data
* makes location data loop use the index instead of copy
=> Fix object storage printer output for tiers

cmd/baremetal/printer.go, cmd/instance/printer.go
* Adds the user scheme and password display for newly created instances and bare metals
* Will show `UNAVAILABLE` when the password eventually stops returning through the API (10 minutes after creation)
=> Add user and password display for instances and bare metals
