- .gitignore
- .goreleaser.yml
- travis.yml
Adding Goreleaser to automate releases of the vultr-cli on new tag
> Goreleaser

- CHANGELOG.md
- cmd/version.go
> release v0.1.1

- CHANGELOG.md
- cmd/version.go
> release v0.1.2

- CHANGELOG.md
- cmd/version.go
> release for v0.1.3

- Makefile
Added in a gofmt in the makefile
#43
> added in gofmt in the makefile

- cmd/printer/script.go
- cmd/script.go
cleaned up output for script list command and moved script content to script contents <scriptid>
> added script contents command, cleaned up script list output

- CHANGELOG.md
- cmd/version.go
v0.1.4 release
Releases
#44 
#43
> release v0.1.4

- CHANGELOG.md
- cmd/root.go
- cmd/version.go
Release for v0.1.5
releases:
#47
> release v0.1.5

- cmd/application.go
- cmd/plans.go
- cmd/regions.go
- cmd/user.go
Add error description where is missing
Fixes #49
> Fix #49 - Print error messages

- cmd/application.go
- cmd/plans.go
- cmd/regions.go
- cmd/user.go
Added newlines to the end of printf statements
#50
> added newlines to updated printf calls

- CHANGELOG.md
- cmd/version.go
v0.1.6 release
Releases #49 #52
> release 0.1.6

- .goreleaser.yml
Automate the HomeBrew Tap update
none
> GoReleaser - Homebrew tap

- CHANGELOG.md
- cmd/version.go
Release for v0.1.7
Releases
#55
> release for v0.1.7

- .goreleaser.yml
fix for goreleaser releasing to brew
none
> fix for brew release

- CHANGELOG.md
- cmd/version.go
release for v0.1.8
Releases
#57
> release for v0.1.8

- CHANGELOG.md
- cmd/version.go
> release for v0.1.9

- CHANGELOG.md
- cmd/version.go
Release for v0.1.10
releases 
#61
> release for v0.1.10

- cmd/network.go
fixed error message for network creation to saying `creating` instead of `deleting`
Fixes
#63
> Network error msg

- CHANGELOG.md
- cmd/version.go
> Release 0.1.11

- CHANGELOG.md
- cmd/version.go
Release for 0.2.0
#74
#75
#75 
#76
#77 
#78
#79
> release for v0.2.0

- CHANGELOG.md
- cmd/version.go
release for v0.2.1
releases #81
> release for v0.2.1

- CHANGELOG.md
- cmd/version.go
Release for v0.3.0
Releases #89 #88 #87 #85
> release for v0.3.0

- CHANGELOG.md
- cmd/version.go
Release for v0.3.1
Releases #94, #95
> release v0.3.1

- CHANGELOG.md
- cmd/version.go
release for v0.3.2
resolves #98
> release for 0.3.2

- .goreleaser.yml
- .travis.yml
- Dockerfile
- Dockerfile.goreleaser
- Makefile
Updating goreleaser to publish docker images on new tags 
- release
- vx.x.x
> goreleaser tag and release docker image

- vendor/github.com/spf13/viper/util.go
- vendor/github.com/spf13/viper/viper.go
- vendor/modules.txt
> vendoring viper

- CHANGELOG.md
- cmd/version.go
update vultr-cli version and changelog for v0.4.0
Relates to #67, #104, #105, #108, #109
* [ x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [x ] Have you linted your code locally prior to submission?
* [ x] Have you successfully ran tests with your changes locally?
> release for v0.4.0

- CHANGELOG.md
- cmd/version.go
> release for v1.0.0

- cmd/dnsRecord.go
Added paging args for dns list
Fixes #122
> add paging args to record list

- .goreleaser.yml
- CHANGELOG.md
- cmd/version.go
Release for v2.0.1
Releases #125 #123
> release for v2.0.1

- cmd/application.go
- cmd/backups.go
- cmd/bareMetal.go
- cmd/blockStorage.go
- cmd/dnsDomain.go
- cmd/dnsRecord.go
- cmd/firewallGroup.go
- cmd/firewallRule.go
- cmd/instance.go
- cmd/iso.go
- cmd/loadBalancer.go
- cmd/network.go
- cmd/objectStorage.go
- cmd/os.go
- cmd/plans.go
- cmd/regions.go
- cmd/reservedIP.go
- cmd/script.go
- cmd/snapshot.go
- cmd/sshKey.go
- cmd/user.go
- cmd/version.go
- go.mod
- go.sum
- vendor/github.com/vultr/govultr/v2/CHANGELOG.md
- vendor/github.com/vultr/govultr/v2/README.md
- vendor/github.com/vultr/govultr/v2/bare_metal_server.go
- vendor/github.com/vultr/govultr/v2/go.sum
- vendor/github.com/vultr/govultr/v2/govultr.go
- vendor/modules.txt
Add bare metal start call, update govultr and cli version
> Add Bare Metal Start call, update paging docs and govultr

- CHANGELOG.md
- cmd/version.go
Release for v2.1.0
Releases #127
> release for v2.1.0

- .github/workflows/notify-pr.yml
- .github/workflows/notify-release.yml
Github Actions to send notifications
> Notifications with GHA

- cmd/bareMetal.go
- cmd/blockStorage.go
adds get call for block storage, fixes typo in bm vnc call
> updates to bm and block calls

- CHANGELOG.md
- cmd/version.go
> release for v2.3.0

- CHANGELOG.md
- Makefile
- README.md
- cmd/version.go
> release for v2.4.0

- cmd/loadBalancer.go
Fixes updating a load balancer
> lbupdate fix

- CHANGELOG.md
- cmd/version.go
> Release for v2.4.1

- CHANGELOG.md
- cmd/version.go
> release for v2.5.0

- CHANGELOG.md
- cmd/version.go
> release for v2.5.1

- .github/workflows/gochecks.yml
- CHANGELOG.md
- Dockerfile
- cmd/version.go
> release for v2.5.2

- CHANGELOG.md
- cmd/version.go
> release for v2.5.3

- CHANGELOG.md
- cmd/version.go
> Release for v2.6.0

- cmd/bareMetal.go
- cmd/bareMetalImage.go
- cmd/instance.go
- cmd/printer/application.go
- cmd/printer/instance.go
- go.mod
- go.sum
- vendor/github.com/hashicorp/go-cleanhttp/cleanhttp.go
- vendor/github.com/hashicorp/go-cleanhttp/go.mod
- vendor/github.com/vultr/govultr/v2/CHANGELOG.md
- vendor/github.com/vultr/govultr/v2/application.go
- vendor/github.com/vultr/govultr/v2/bare_metal_server.go
- vendor/github.com/vultr/govultr/v2/govultr.go
- vendor/github.com/vultr/govultr/v2/instance.go
- vendor/modules.txt
- Updates govultr to 2.7.1
- Adds support for image_id
> Update govultr and add image_id support

- CHANGELOG.md
- README.md
- cmd/version.go
> Release for v2.7.0

- README.md
makes the examples for building from source a bit more explicit
I was trying to build from source and got a bit confused by the examples shown.
> update commands needed for building from source

- cmd/kubernetes.go
- cmd/printer/kubernetes.go
- cmd/root.go
> VKE support

- CHANGELOG.md
- cmd/version.go
Release for v2.8.0
#178 #177 #174 #173
> release for v2.8.0

- cmd/root.go
- cmd/version.go
> add useragent

- CHANGELOG.md
- cmd/version.go
> Release for v2.8.1

- README.md
Add instructions to readme to use boolean flags
> update readme for boolean flags

- CHANGELOG.md
- cmd/version.go
> Release v2.8.2

- CHANGELOG.md
- cmd/version.go
> Release v2.8.4

- CHANGELOG.md
- cmd/version.go
> Release v2.10.0

- .github/workflows/goreleaser.yml
- .goreleaser.yml
- scripts/entrypoint.sh
Updated how docker is logged into during goreleaser action
> Reworked Docker for goreleaser

- cmd/instance.go
- go.mod
- go.sum
- vendor/github.com/vultr/govultr/v2/CHANGELOG.md
- vendor/github.com/vultr/govultr/v2/domains.go
- vendor/github.com/vultr/govultr/v2/govultr.go
- vendor/github.com/vultr/govultr/v2/instance.go
- vendor/modules.txt
Updates govultr dependency to 2.11
> update govultr to 2.11

- cmd/instance.go
Adds host flag to reinstall call
> change hostname to host, add flag to command

- cmd/printer/dnsDomain.go
Adds support for displaying whether dns sec is enabled or disabled for get/list/create calls
#207
> add dns sec support for get/list/create calls

- CHANGELOG.md
- cmd/version.go
Release v2.11.0
#207 #209  #210 #211
> release v2.11.0

- CHANGELOG.md
- cmd/version.go
> release : v2.11.1

- go.mod
- go.sum
- vendor/github.com/vultr/govultr/v2/CHANGELOG.md
- vendor/github.com/vultr/govultr/v2/govultr.go
- vendor/github.com/vultr/govultr/v2/plans.go
- vendor/modules.txt
> update govultr to v2.12.0

- CHANGELOG.md
- cmd/version.go
> Release v2.11.2

- CHANGELOG.md
- cmd/version.go
> Release v2.11.3 #patch

- .github/workflows/releaser.yml
This PR should resolve the docker login issues during release.
> Fixed docker for releaser

- cmd/firewallRule.go
Changes flag from int to string
> Firewalls : change source from int to string

- cmd/printer/script.go
Return b64 script when getting script by id
> Return b64 script when getting script by id

- CHANGELOG.md
- cmd/version.go
Release v2.12.0
#230, #229, #228, #224, #223
> Release v2.12.0 #minor

- cmd/printer/firewallRule.go
This PR adds IP type, source and subnet size to the firewall rule printer
> Add IP type, source and subnet size to firewall rule printer

- cmd/plans.go
- cmd/regions.go
Adds missing types and removes old types for displaying plans and availability in regions
> Adding missing types and removing old types for plans

- cmd/plans.go
- cmd/plansMetal.go
Adding some additional examples to the plan and plan metal commands for clarity 
n/a
> Plans + Plans Metal examples

- CHANGELOG.md
- cmd/version.go
> Release v2.12.2 #patch

- README.md
Add installation instructions for Fedora.
* https://src.fedoraproject.org/rpms/vultr-cli
No related issues.
> 🐧 Add Fedora installation instructions

- cmd/blockStorage.go
- go.mod
- go.sum
- vendor/github.com/vultr/govultr/v2/CHANGELOG.md
- vendor/github.com/vultr/govultr/v2/block_storage.go
- vendor/github.com/vultr/govultr/v2/govultr.go
- vendor/github.com/vultr/govultr/v2/instance.go
- vendor/github.com/vultr/govultr/v2/load_balancer.go
- vendor/github.com/vultr/govultr/v2/network.go
- vendor/github.com/vultr/govultr/v2/vpc.go
- vendor/modules.txt
This PR adds support for block type on block storage creation.
This PR also adds new aliases and examples for block storage commands
> Add block type support / Add Aliases and Examples

- cmd/loadBalancer.go
Add flag checking for --vpc and --private-network
> Add VPC flag check to Load Balancers

- cmd/printer/blockStorage.go
> Block Storage: adding block type to the response

- CHANGELOG.md
- cmd/version.go
Release for v2.13.0
#253
#252 
#251 
#249 
#246
> Release v2.13.0

- README.md
- cmd/instance.go
Update verbiage around snapshots to make it more clear
#256
> updated veribage for snapshots + readme

- go.mod
- go.sum
Bumps [github.com/vultr/govultr/v2](https://github.com/vultr/govultr) from 2.16.0 to 2.17.1.
- [Release notes](https://github.com/vultr/govultr/releases)
- [Changelog](https://github.com/vultr/govultr/blob/master/CHANGELOG.md)
> Bump govultr version from 2.16.0 to 2.17.1

- cmd/instance.go
- cmd/kubernetes.go
- vendor/github.com/vultr/govultr/v2/CHANGELOG.md
- vendor/github.com/vultr/govultr/v2/bare_metal_server.go
- vendor/github.com/vultr/govultr/v2/govultr.go
- vendor/github.com/vultr/govultr/v2/instance.go
- vendor/github.com/vultr/govultr/v2/kubernetes.go
- vendor/github.com/vultr/govultr/v2/plans.go
- vendor/modules.txt
Fixes string types from govultr 2.17.0
> Update instance and kubernetes tag to str pointer

- cmd/printer/plans.go
Add the GPU fields that are now supported by the API and govultr
> Add GPU fields to plans printer

- CHANGELOG.md
- cmd/version.go
> Release v2.14.2 #patch

- CHANGELOG.md
- cmd/version.go
New release to test out the ARM builds
#283 
#274
#284 
#279 
#278 -- will need to test
> Release v2.15.0 #minor

- .goreleaser.yml
> Update goreleaser to add latest docker image tag

- cmd/plans.go
- cmd/regions.go
Update the helptext to include the GPU plans code `vcg`
> Add vcg options to docstrings on regions and plans

- CHANGELOG.md
- cmd/version.go
Release v2.15.1 #patch
#287 
#291 
#299 
#288 
#289 
#290 
#296 
#298 
#293 
#297
> Release v2.15.1 #patch

- go.mod
> Update go to 1.20

- CHANGELOG.md
- cmd/version.go
Release v2.16.0 #minor
#302 
#303 
#301 
#304
> Release v2.16.0 #minor

- .github/workflows/releaser.yml
- .goreleaser.yml
Update the goreleaser config and workflow to remove the extraneous hooks now that the vendor directory has been removed.  I'm not sure this will work in the repo but testing with `goreleaser release --snapshot --skip-publish` seems okay.
> Goreleaser configuration updates

- CHANGELOG.md
- cmd/version.go
> Release v2.16.1 #patch

- .github/workflows/releaser.yml
- .goreleaser.yml
The yaml `go-version: 1.20` is getting interpreted as a float.  Explicitly define it as a string
> Quote go version in github workflow config

- CHANGELOG.md
- cmd/version.go
> Release v2.16.2 #patch

- .github/workflows/coverage.yml
- .github/workflows/gochecks.yml
Update some github workflow go versions to use v1.20
> Update workflows to go v1.20

- README.md
Tiny doc tweak — on macOS, this command is equivalent to the two separate commands being replaced.
> Use a more succinct Homebrew command to tap-and-install

- README.md
Add some basic installation and usage instructions for the Docker image.
Closes #321
> Add docker install/usage instructions

- README.md
> Fix README spelling

- CHANGELOG.md
- cmd/version.go
Release v2.17.0 #minor
#318 
#314 
#315 
#324 
#322 
#325 
#320 
#310 
#319 
#312 
#316 
#323 
#311
> Release v2.17.0 #minor

- go.mod
- go.sum
> Update govultr to v3.1.0

- go.mod
- go.sum
> Update govultr to v3.3.0

- cmd/application.go
Adds a couple more aliases for the `apps` command to increase usability
> Add more aliases for the apps command

- go.mod
- go.sum
Bump to the latest govultr to build support for the VPC2 nodes functionality.
> Update govultr to v3.3.1

- cmd/printer/vpc2.go
- cmd/root.go
- cmd/vpc2.go
Add in support for nodes listing, attaching, and detaching for Vultr VPC 2.0 networks.
> VPC2 Nodes Endpoints

- cmd/database.go
- cmd/root.go
This PR restructures Managed Database components to be more consistent with the nesting pattern present throughout the rest of Vultr-CLI. There are also a few linting fixes and duplicate description corrections.
> Managed Database Nesting Refactor

- CHANGELOG.md
- cmd/version.go
Release v2.18.0 #minor
#331 
#335 
#339 
#340 
#337 
#336 
#334 
#338 
#329 
#330 
#328 
#333
> Release v2.18.0 #minor

- .goreleaser.yml
The replacement option for archives has been removed from goreleaser.  This will use `name_template` conditional statements instead.
> Remove replacement and use name template in goreleaser archives

- go.mod
- go.sum
> Update govultr to v3.3.2

- cmd/database.go
- go.mod
- go.sum
> Update govultr to v3.3.3

- go.mod
- go.sum
> Update govultr to v3.3.4

- CHANGELOG.md
- cmd/version.go
Release v2.20.0 #minor
#363 
#364 
#368 
#369 
#366 
#358 
#362 
#365 
#367 
#356 
#357
> Release v2.20.0 #minor

- go.mod
- go.sum
> Bump govultr to v3.4.0

- cmd/kubernetes.go
Allows the user to specify kubeconfig file path.
> add kubeconfig filepath flag

- CHANGELOG.md
- cmd/version.go
Release v2.21.0 #minor
#378 
#380 
#372 
#375 
#361 
#376 
#379 
#371 
#374 
#373
> Release v2.21.0 #minor

- cmd/containerRegistry.go
fixes issue where `read-write` flag wasn't being honored
> 394 - use read-write flag instead

- CHANGELOG.md
- cmd/version.go
Release v2.22.0 #minor
#383 
#389 
#395 
#382 
#388 
#393 
#392 
#390
> Release v2.22.0 #minor

- cmd/plans/plans.go
> Remove unused validate on plans

- CHANGELOG.md
- cmd/version/version.go
Release v3.0.0 #major
#402 
#397
> Release v3.0.0 #major

- README.md
> Update go get command to v3.

- cmd/firewall/firewall.go
Fixes command usage for the firewall rules
Closes #411
> Add correct usage for firewall rules

- CHANGELOG.md
- cmd/version/version.go
Release v3.0.1 #patch
#413 
#410 
#406 
#412 
#407 
#405 
#414
> Release v3.0.1 #patch

- go.mod
- go.sum
Updates govultr from v3.6.2 to v3.6.3
> Update govultr from v3.6.2 to v3.6.3

- go.mod
- go.sum
Update govultr from v3.6.3 to v3.6.4
> Update govultr from v3.6.3 to v3.6.4

- README.md
Remove extraneous readme details
> Remove extraneous readme details

- CHANGELOG.md
- cmd/version/version.go
Release v3.0.2 #patch
#422 
#426 
#416 
#419 
#425 
#418 
#421 
#417 
#420
> Release v3.0.2 #patch

- pkg/cli/cli.go
The wrong variable was being passed in as the auth token.
Closes #429
> Fix oauth token when a config file is used

- CHANGELOG.md
- cmd/version/version.go
Release v3.0.3 #patch
#430 
#428
> Release v3.0.3 #patch

- .github/workflows/notify-issue.yml
- .github/workflows/notify-pr.yml
- .github/workflows/releaser.yml
Make mattermost notifications generic
#444 
#441
> Make mattermost notifications generic

- cmd/kubernetes/kubernetes.go
- cmd/kubernetes/printer.go
I thought this would be useful for quick glance node pool list, like what we use for the kubernetes clusters
`go run main.go kubernetes node-pools <UUID> --summarize`
> Add node-pool list summarize flag

- CHANGELOG.md
- cmd/version/version.go
Release v3.1.0 #minor
#432 
#434 
#436 
#437 
#442 
#441 
#445 
#440 
#443
> Release v3.1.0 #minor

- go.mod
- go.sum
Update govultr from v2.7.0 to v2.8.1
> Update govultr from v2.7.0 to v2.8.1

- README.md
- cmd/inference/inference.go
- cmd/inference/printer.go
- cmd/root.go
This PR adds support for the Vultr Serverless Inference product for the purpose of managing the subscription and viewing usage information.
> Support Vultr Serverless Inference

- .gitignore
Add linux binary name to gitignore
> Ignore linux binary

- .github/workflows/releaser.yml
- .goreleaser.yml
Update the goreleaser config for v2 and bump the github action to the latest.
Check the config with `goreleaser check .goreleaser.yml` to confirm all is well.
> Update goreleaser config and action

- .golangci.yaml
- cmd/applications/applications.go
- cmd/backups/backups.go
- cmd/baremetal/baremetal.go
- cmd/billing/billing.go
- cmd/blockstorage/blockstorage.go
- cmd/containerregistry/containerregistry.go
- cmd/containerregistry/printer.go
- cmd/database/database.go
- cmd/dns/dns.go
- cmd/firewall/firewall.go
- cmd/instance/instance.go
- cmd/iso/iso.go
- cmd/kubernetes/kubernetes.go
- cmd/loadbalancer/loadbalancer.go
- cmd/loadbalancer/printer.go
- cmd/objectstorage/objectstorage.go
- cmd/operatingsystems/operatingsystems.go
- cmd/plans/plans.go
- cmd/regions/regions.go
- cmd/reservedip/reservedip.go
- cmd/script/script.go
- cmd/sshkeys/sshKeys.go
- cmd/users/user.go
- cmd/vpc/vpc.go
- cmd/vpc2/vpc2.go
* Update lint configuration
* Fix long lines
* Fix magic number
> Linter updates and fixes

- .github/workflows/gochecks.yml
Updates the actions for the github go linting automations
#457
> Update the go-checks actions

- CHANGELOG.md
- cmd/version/version.go
Release v3.2.0 #minor
#453 
#449 
#451 
#448 
#450 
#454 
#457 
#456 
#455
> Release v3.2.0 #minor

- go.mod
- go.sum
Update govultr from v3.8.1 to v3.9.0
> Update govultr from v3.8.1 to v3.9.0

- cmd/cdn/cdn.go
- cmd/cdn/printer.go
- cmd/root.go
Adds commands to the CLI which allow access to the CDN API functions
> Add commands for CDN API functions

- README.md
Add CDN command to README
#462
> Add CDN command to README

- cmd/database/database.go
Fix invalid flag definition for mysql long run time
Resolves #464
> Change mysql long run flag to int

- CHANGELOG.md
- cmd/version/version.go
Release v3.3.0 #minor
#462 
#465 
#463 
#461
> Release v3.3.0 #minor

- CHANGELOG.md
- cmd/version/version.go
* Release v3.3.1 #patch
#460 
#468
> Release v3.3.1 #patch

- go.mod
- go.sum
Update govultr from v3.9.0 to v3.9.1
> Update govultr from v3.9.0 to v3.9.1

- cmd/loadbalancer/loadbalancer.go
- cmd/loadbalancer/printer.go
* Add `nodes` flags on `load-balancer create` and `update`
* Add number of nodes display to `load-balancer get` and `list`
> Add loadbalancer nodes flags and display

- cmd/baremetal/printer.go
- cmd/cdn/cdn.go
- cmd/database/printer.go
- go.mod
- go.sum
* Updates govultr
* Resolves some type changes
* Removes deprecated field usage
> Update govultr from v3.9.1 to v3.11.0

- .golangci.yaml
Remove deprecated exportloopref linter
> Remove deprecated exportloopref linter

- go.mod
- go.sum
Updates govultr from v3.11.0 to v3.11.1
> Update govultr from v3.11.0 to v3.11.1

- go.mod
- go.sum
Update govultr from v3.11.1 to v3.11.2
> Update govultr from v3.11.1 to v3.11.2

- cmd/database/database.go
- cmd/database/printer.go
This PR adds support for Kafka subscriptions to our broader Vultr Managed Database endpoints. It should handle all required structural changes as well as new endpoints and advanced configuration options.
> Support Managed Kafka

- CHANGELOG.md
- cmd/version/version.go
Release v3.4.0 #minor
#472 
#474 
#487 
#470 
#473 
#471 
#481 
#485 
#486 
#477 
#484 
#475 
#479 
#482
> Release v3.4.0 #minor

- go.mod
- go.sum
Update govultr from v3.11.2 to v3.12.0
> Update govultr from v3.11.2 to v3.12.0

- .github/workflows/gochecks.yml
- .github/workflows/releaser.yml
- go.mod
Update go version and workflow actions to latest
> Update go to v1.24

- go.mod
- go.sum
Update govultr from v3.14.1 to v3.15.0
> Update govultr from v3.14.1 to v3.15.0

- cmd/account/account.go
This needs to be set in order to parse the global flag `--output`
> Set global options on account command

- cmd/baremetal/baremetal.go
- cmd/instance/instance.go
- cmd/vpc2/vpc2.go
Mark VPC2 related commands as deprecated.
> Mark vpc2 commands deprecated

- cmd/baremetal/baremetal.go
- cmd/dns/dns.go
- cmd/kubernetes/kubernetes.go
Fix some erroneous variable checks for error values.
> Fix err nil checks

- go.mod
- go.sum
Update govultr from v3.17.0 to v3.20.0
> Update govultr from v3.17.0 to v3.20.0

- cmd/database/database.go
- cmd/database/printer.go
This PR adds support for setting and viewing custom backup schedules for Managed Databases.
> Add support for Managed Database backup schedule

- cmd/containerregistry/containerregistry.go
- cmd/objectstorage/objectstorage.go
- cmd/objectstorage/printer.go
* Re-arranges the object storage cluster commands to include the tier list 
* Adds object storage tier command to list all tiers 
* Fixes an incorrect helptext in container registry
> Update object storage cluster display and add tiers

- .github/workflows/gochecks.yml
- .golangci.yaml
- cmd/kubernetes/kubernetes.go
- cmd/kubernetes/printer.go
- cmd/loadbalancer/loadbalancer.go
- cmd/objectstorage/printer.go
- cmd/printer/printer.go
* Update the github workflow/action 
* Migrate the configuration yaml to v2
* Fix issues that arise from the latest version
> Update Golangci-lint to use v2

- cmd/containerregistry/containerregistry.go
- cmd/objectstorage/objectstorage.go
* adds examples to the help text for object storage
* fixes a typo in the container registry help text
> Add example help text for object storage

- cmd/database/database.go
- cmd/database/printer.go
This PR implements robust support for the latest additions to the Managed Kafka API, including new fields for enabling/disabling Kafka REST, Schema Registry, and Kafka Connect, an update endpoint for quotas, and all Kafka connector endpoints. The full list of newly supported endpoints are as follows:
- `UpdateQuota`: New update endpoint for quotas (previous behavior required deleting and re-adding)
- `ListAvailableConnectors`: Shows all Kafka Connect connectors available for a subscription
- `GetConnectorConfigurationSchema`: Returns the configuration schema fields for a given connector
- `ListConnectors`: Lists all currently active connectors for a subscription
- `CreateConnector`, `GetConnector`, `UpdateConnector`, `DeleteConnector`: Basic CRUD for managing a connector
- …
> Managed Databases: Add Expanded Support for Kafka Features 

- go.mod
- go.sum
Update govultr from v3.21.0 to v3.21.1
> Update govultr from v3.21.0 to v3.21.1

- CHANGELOG.md
- cmd/version/version.go
Release v3.6.0 #minor
#545 
#541 
#543 
#542 
#545 
#544
> Release v3.6.0 #minor

- cmd/snapshot/snapshot.go
Ignore gocyclo on snapshot cmd
> Ignore gocyclo on snapshot cmd

- CHANGELOG.md
- cmd/version/version.go
Release v3.7.0 #minor
#552 
#547 
#553 
#549 
#548 
#551 
#554
> Release v3.7.0 #minor

- go.mod
- go.sum
Update govultr from v3.23.0 to v3.24.0
> Update govultr from v3.23.0 to v3.24.0

- CHANGELOG.md
- cmd/version/version.go
Release v3.8.0 #minor
#559 
#556 
#557 
#558
> Release v3.8.0 #minor
